# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'
- task: TerraformTaskV2@2
  inputs:
    provider: 'aws'
    command: 'init'
    backendServiceAWS: 'aws test'
- task: TerraformTaskV2@2
  inputs:
    provider: 'aws'
    command: 'validate'
- task: TerraformTaskV2@2
  inputs:
    provider: 'aws'
    command: 'apply'
    environmentServiceNameAWS: 'aws test'
- task: ManualIntervention@8
  inputs:
    timeoutInMinutes: 120
    instructions: 'Borrar infra?'
    emailRecipients: 'demonccc.y@gmail.com'
    onTimeout: 'resume'
- task: TerraformTaskV2@2
  inputs:
    provider: 'aws'
    command: 'destroy'
    environmentServiceNameAWS: 'aws test'
